services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: productDB
    ports:
      - "5432:5432"
    volumes:
      - produtos_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d produtos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_test:
    image: postgres:15
    container_name: db_test
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: productDB_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d produtos_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  produtos_data: